FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD DevOpsGKEGit.jar /opt/DevOpsGKEGit/
EXPOSE 8080
WORKDIR /opt/DevOpsGKEGit/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "DevOpsGKEGit.jar"]
